#!/usr/bin/env bash
# Sets up a clean demo plan for the VHS recording
set -e
cd ~/Projects/gatefile
mkdir -p .demo
node -e "
const {createPlanFromDraft} = require('./dist');
const draft = {
  version: '0.1',
  source: 'coding-agent',
  summary: 'Add auth module and run typecheck',
  operations: [
    { id: 'op_1', type: 'file', action: 'create', path: '.demo/src/auth.ts', after: 'export function authenticate(token: string) { return true; }\n' },
    { id: 'op_2', type: 'file', action: 'create', path: '.demo/src/README.md', after: '# Auth Module\nGenerated by coding agent.\n' },
    { id: 'op_3', type: 'command', command: 'echo typecheck passed', allowFailure: false }
  ],
  preconditions: [],
  execution: { commandPolicy: { mode: 'allow', patterns: ['echo'] } }
};
const plan = createPlanFromDraft(draft);
require('fs').writeFileSync('.demo/plan.json', JSON.stringify(plan, null, 2));
"
echo "Demo plan created at .demo/plan.json"
